[env]
MNN_INCLUDE_DIR = { value = "vendor/mnn/3.6.0/windows-x64/include", relative = true }
MNN_LIB_DIR = { value = "vendor/mnn/3.6.0/windows-x64/lib", relative = true }
FFMPEG_DIR = { value = "vendor/ffmpeg/8.1/windows-x64", relative = true }
